spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 966041633083-meuqrchq23lipq1tsc1pabn24ojmcht3.apps.googleusercontent.com
            client-secret: UhTG51TMiP9JznCisWeJoK
            scope: profile,email

